// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAmljBniu_gAkKMZsqrEQMqbCsCTk8AA8',
    appId: '1:264564640456:web:d3d72f5b90560ae324f3fd',
    messagingSenderId: '264564640456',
    projectId: 'tradezy-e0e76',
    authDomain: 'tradezy-e0e76.firebaseapp.com',
    storageBucket: 'tradezy-e0e76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgrPGwnWHHUS5nBlLLE3HNjabV8ftm3JQ',
    appId: '1:264564640456:android:d25435813313053724f3fd',
    messagingSenderId: '264564640456',
    projectId: 'tradezy-e0e76',
    storageBucket: 'tradezy-e0e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8bnsFdMMRUTmx2snyERFdOU7ejUl6hg0',
    appId: '1:264564640456:ios:fc71adfe70e19c6524f3fd',
    messagingSenderId: '264564640456',
    projectId: 'tradezy-e0e76',
    storageBucket: 'tradezy-e0e76.appspot.com',
    iosBundleId: 'com.example.tradezyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8bnsFdMMRUTmx2snyERFdOU7ejUl6hg0',
    appId: '1:264564640456:ios:fc71adfe70e19c6524f3fd',
    messagingSenderId: '264564640456',
    projectId: 'tradezy-e0e76',
    storageBucket: 'tradezy-e0e76.appspot.com',
    iosBundleId: 'com.example.tradezyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAmljBniu_gAkKMZsqrEQMqbCsCTk8AA8',
    appId: '1:264564640456:web:2de8e9880cc34a2c24f3fd',
    messagingSenderId: '264564640456',
    projectId: 'tradezy-e0e76',
    authDomain: 'tradezy-e0e76.firebaseapp.com',
    storageBucket: 'tradezy-e0e76.appspot.com',
  );
}
